### ISSUE TITLE
Missão 00 - Linguagem de Programação III

### ISSUE THREAD

**Issue by debs-veras** [gilzamir18/GameMania#2]
Como faço para contribuir com este repositório?

**Comment by gilzamir18** [comment]
Basta aceitar colaborar com o projeto (convite já enviado) e realizar as issues atribuídas durante a realização do projeto. Observe, realize as issues em seu próprio fork e depois solicite pull request (irei aceitar incorporar no repositório principal o pull request das melhores implementações - mesmo que a resolução seja aceita para fins de pontuação.).

**Comment by gilzamir18** [comment]
Aguardando a aluna aceitar o convite para colaborar com o repositório.

**Comment by weslleyrufinow** [comment]
Como faço para contribuir com este repositório? (Apenas seguindo o protocolo 😌)
