### ISSUE TITLE
Como posso contribuir com este repositório?

### ISSUE THREAD

**Issue by TeonetoAlbuquerque** [gilzamir18/GameMania#3]

**Comment by gilzamir18** [comment]
Basta aceitar colaborar com o projeto (convite já enviado) e realizar as issues atribuídas durante a realização do projeto. Observe, realize as issues em seu próprio fork e depois solicite pull request (irei aceitar o pull request das melhores implementações).

**Comment by gilzamir18** [comment]
O aluno fez a primeira contribuição, apesar de não enviado o PR.
