### ISSUE TITLE
Como faço para contribuir com este repositório

### ISSUE THREAD

**Issue by juancamilojc** [gilzamir18/GameMania#4]

**Comment by gilzamir18** [comment]
Olá, o primeiro passo é aceitar colaborar com o repositório (convite já enviado) e realizar as issues atribuídas durante a realização do projeto. Observe, realize as issues em seu próprio fork/branch e depois solicite pull request (irei aceitar incorporar no repositório principal o pull request das melhores implementações - mesmo que a resolução seja aceita para fins de pontuação.).
